/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;


import CLASES.CONEXION_MySQL;
import CLASES.GENERAL_CLASS;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAVIER
 */
public class BuscarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form BuscarUsuario
     */
    public BuscarUsuario(UserCheck bd1) {
        initComponents();
        bd= bd1;
        //CONEXION_MySQL Con = new CONEXION_MySQL();
    }

    public BuscarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarUsuario = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        idUsuarioBuscar = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCodigos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        NDocumento2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDocumento = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        BusNombreUsuario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableNombre = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableTipo = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        BuscarCliente = new javax.swing.JRadioButton();
        BuscarProveedor = new javax.swing.JRadioButton();
        BuscarEmpleado = new javax.swing.JRadioButton();
        NDocumentoBuscar = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableEmail = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        BuscarEmail = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableBancaria = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        NumeroCuentas = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        NBanco1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BuscarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BuscarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idUsuarioBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idUsuarioBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idUsuarioBuscarFocusLost(evt);
            }
        });
        idUsuarioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioBuscarActionPerformed(evt);
            }
        });
        idUsuarioBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idUsuarioBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idUsuarioBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idUsuarioBuscarKeyTyped(evt);
            }
        });
        jPanel2.add(idUsuarioBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, 20));

        jLabel61.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel61.setText("CODIGO");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 38));

        jButton2.setText("EXPORTAR INFORME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 38));

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 38));

        TableCodigos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableCodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCodigos.setRowHeight(18);
        TableCodigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCodigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCodigos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 570, 230));

        jTabbedPane1.addTab("Codigo", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel62.setText("Nº Documento");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 7, -1, -1));

        NDocumento2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NDocumento2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NDocumento2FocusLost(evt);
            }
        });
        NDocumento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NDocumento2ActionPerformed(evt);
            }
        });
        NDocumento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NDocumento2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NDocumento2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NDocumento2KeyTyped(evt);
            }
        });
        jPanel3.add(NDocumento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 7, 200, -1));

        TableDocumento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDocumento.setRowHeight(18);
        jScrollPane2.setViewportView(TableDocumento);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 37, 570, 230));

        jButton4.setText("EXPORTAR INFORME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 277, -1, 38));

        jButton5.setText("LIMPIAR");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 277, -1, 38));

        jButton6.setText("ENVIAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 277, -1, 38));

        jButton22.setText("BUSCA");
        jPanel3.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 38));

        jTabbedPane1.addTab("NDocumento", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel63.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel63.setText("Nombre Completo");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 7, -1, -1));

        BusNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BusNombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BusNombreUsuarioFocusLost(evt);
            }
        });
        BusNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusNombreUsuarioActionPerformed(evt);
            }
        });
        BusNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BusNombreUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BusNombreUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusNombreUsuarioKeyTyped(evt);
            }
        });
        jPanel4.add(BusNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 7, 200, -1));

        TableNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableNombre.setRowHeight(18);
        jScrollPane3.setViewportView(TableNombre);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 37, 570, 230));

        jButton7.setText("EXPORTAR INFORME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 277, -1, 38));

        jButton8.setText("LIMPIAR");
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 277, -1, 38));

        jButton9.setText("ENVIAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 277, -1, 38));

        jButton23.setText("BUSCA");
        jPanel4.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 38));

        jTabbedPane1.addTab("Nombre Usuario", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "ESTADO", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableTipo.setRowHeight(18);
        jScrollPane6.setViewportView(TableTipo);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 570, 230));

        jButton16.setText("EXPORTAR INFORME");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 38));

        jButton17.setText("BUSCA");
        jPanel6.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 38));

        jButton18.setText("ENVIAR");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 38));

        jButton19.setText("LIMPIAR");
        jPanel6.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 38));

        BuscarCliente.setText("CLIENTE");
        BuscarCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BuscarClienteItemStateChanged(evt);
            }
        });
        jPanel6.add(BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        BuscarProveedor.setText("PROVEEDOR");
        BuscarProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BuscarProveedorItemStateChanged(evt);
            }
        });
        jPanel6.add(BuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BuscarEmpleado.setText("EMPLEADO");
        BuscarEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BuscarEmpleadoItemStateChanged(evt);
            }
        });
        jPanel6.add(BuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        NDocumentoBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NDocumentoBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NDocumentoBuscarFocusLost(evt);
            }
        });
        NDocumentoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NDocumentoBuscarActionPerformed(evt);
            }
        });
        NDocumentoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NDocumentoBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NDocumentoBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NDocumentoBuscarKeyTyped(evt);
            }
        });
        jPanel6.add(NDocumentoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 160, 20));

        jLabel66.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel66.setText("Nº Documento");
        jPanel6.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, -1));

        jTabbedPane1.addTab("Tipo de Usuario", jPanel6);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "ESTADO", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableEmail.setRowHeight(18);
        jScrollPane5.setViewportView(TableEmail);

        jPanel8.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 37, 570, 230));

        jButton13.setText("EXPORTAR INFORME");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 277, -1, 38));

        jButton14.setText("LIMPIAR");
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 277, -1, 38));

        jButton15.setText("ENVIAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 277, -1, 38));

        jLabel65.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel65.setText("Email");
        jPanel8.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 7, -1, -1));

        BuscarEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarEmailFocusLost(evt);
            }
        });
        BuscarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEmailActionPerformed(evt);
            }
        });
        BuscarEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarEmailKeyTyped(evt);
            }
        });
        jPanel8.add(BuscarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 200, -1));

        jButton24.setText("BUSCA");
        jPanel8.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 38));

        jTabbedPane1.addTab("Email", jPanel8);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableBancaria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableBancaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DOCUMENTO", "NOMBRE", "NCUENTA", "NOMBRE BANCO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableBancaria.setRowHeight(18);
        jScrollPane4.setViewportView(TableBancaria);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 570, 230));

        jButton10.setText("EXPORTAR INFORME");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 38));

        jButton11.setText("LIMPIAR");
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, 38));

        jButton12.setText("ENVIAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 277, -1, 38));

        jLabel64.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel64.setText("Numero Cuenta");
        jPanel7.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        NumeroCuentas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumeroCuentasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumeroCuentasFocusLost(evt);
            }
        });
        NumeroCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCuentasActionPerformed(evt);
            }
        });
        NumeroCuentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroCuentasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NumeroCuentasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroCuentasKeyTyped(evt);
            }
        });
        jPanel7.add(NumeroCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, -1));

        jLabel70.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel70.setText("Nombre Banco");
        jPanel7.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        NBanco1.setBackground(new java.awt.Color(204, 204, 204));
        NBanco1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NBanco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "BANCO AGRARIO", "NEQUI", "BANCO AV VILLAS", "BANCO CAJA SOCIAL", "SCOTIABANK COLPATRIA", "BANCO COOPERATIVO COOPCETRAL", "BANCO DAVIVIENDA", "BANCO DE BOGOTA", "BANCO DE OCCIDENTE", "BANCO FALABELLA", "BANCO PICHINCHA S.A.", "BANCO BBVA COLOMBIA S.A.", "CITIBANK", "BANCO ITAU", "CONFIAR COOPERATIVA FINANCIERA", "DAVIPLATA", "BANCO DE LAS MICROFINANZAS BANCAMIA", "COLTEFINANCIERA", "CFA COOPERATIVA FINANCIERA", "BANCO CREDIFINANCIERA", "RAPPIPAY", "COTRAFA", "BANCO SANTANDER COLOMBIA", "BANCO SERFINANZA", "GIROS Y FINANZAS" }));
        NBanco1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        org.jdesktop.swingx.autocomplete.AutoCompleteDecorator.decorate(NBanco1);
        NBanco1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NBanco1ItemStateChanged(evt);
            }
        });
        jPanel7.add(NBanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 200, 30));

        jTabbedPane1.addTab("Cuenta Bancaria ", jPanel7);

        BuscarUsuario.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 350));

        getContentPane().add(BuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void LimpiarTable(){
           DefaultTableModel  modelo ;
         modelo =(DefaultTableModel) TableCodigos.getModel();
         modelo.setRowCount(0);
            modelo =(DefaultTableModel) TableDocumento.getModel();
         modelo.setRowCount(0);
                modelo =(DefaultTableModel) TableBancaria.getModel();
         modelo.setRowCount(0);
            modelo =(DefaultTableModel) TableNombre.getModel();
         modelo.setRowCount(0);
                  modelo =(DefaultTableModel) TableEmail.getModel();
         modelo.setRowCount(0);
            modelo =(DefaultTableModel) TableTipo.getModel();
         modelo.setRowCount(0);

}
    private void idUsuarioBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idUsuarioBuscarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioBuscarFocusGained

    private void idUsuarioBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idUsuarioBuscarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioBuscarFocusLost

    private void idUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioBuscarActionPerformed

    private void idUsuarioBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUsuarioBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioBuscarKeyPressed

    private void idUsuarioBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUsuarioBuscarKeyReleased
        int indicado[] ={1,2,3,7};
       bd. BuscarUsuarios( indicado,"IdUsuario",idUsuarioBuscar.getText(),TableCodigos);
    }//GEN-LAST:event_idUsuarioBuscarKeyReleased

    private void idUsuarioBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idUsuarioBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioBuscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       bd.UsuarioBs( bd.GetTables( TableCodigos),"IdUsuario","¿Desea modificarlo?",this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LimpiarTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TableCodigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCodigosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCodigosMouseClicked

    private void NDocumento2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NDocumento2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2FocusGained

    private void NDocumento2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NDocumento2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2FocusLost

    private void NDocumento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NDocumento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2ActionPerformed

    private void NDocumento2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumento2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2KeyPressed

    private void NDocumento2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumento2KeyReleased
        int indicado[] ={1,2,3,7};
        bd.BuscarUsuarios( indicado,"NDocumento",NDocumento2.getText(),TableDocumento);        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2KeyReleased

    private void NDocumento2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumento2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumento2KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 bd.UsuarioBs( bd.GetTables( TableDocumento),"IdUsuario","¿Desea modificarlo?",this);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BusNombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusNombreUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioFocusGained

    private void BusNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BusNombreUsuarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioFocusLost

    private void BusNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioActionPerformed

    private void BusNombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusNombreUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioKeyPressed

    private void BusNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusNombreUsuarioKeyReleased
        int indicado[] ={1,2,3,7};
       bd. BuscarUsuarios( indicado,"NombreUsuari",BusNombreUsuario.getText(),TableNombre);        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioKeyReleased

    private void BusNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusNombreUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BusNombreUsuarioKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 bd.UsuarioBs( bd.GetTables( TableNombre),"IdUsuario","¿Desea modificarlo?",this);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
         bd.UsuarioBs( bd.GetTables( TableTipo),"IdUsuario","¿Desea modificarlo?",this);  
//        general.Informes("src\\Reportes\Municipios.jasper",);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void BuscarClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BuscarClienteItemStateChanged
        int indicado[] ={1,2,3,7,10};
        bd.BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Cliente",
            Boolean.toString(BuscarCliente.isSelected()),TableTipo);         // TODO add your handling code here:
    }//GEN-LAST:event_BuscarClienteItemStateChanged

    private void BuscarProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BuscarProveedorItemStateChanged

        int indicado[] ={1,2,3,7,8};
       bd. BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Proveedor",
            Boolean.toString(BuscarProveedor.isSelected()),TableTipo);
    }//GEN-LAST:event_BuscarProveedorItemStateChanged

    private void BuscarEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BuscarEmpleadoItemStateChanged
        int indicado[] ={1,2,3,7,9};
       bd. BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Empleado",
            Boolean.toString(BuscarEmpleado.isSelected()),TableTipo);
    }//GEN-LAST:event_BuscarEmpleadoItemStateChanged

    private void NDocumentoBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NDocumentoBuscarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarFocusGained

    private void NDocumentoBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NDocumentoBuscarFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarFocusLost

    private void NDocumentoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NDocumentoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarActionPerformed

    private void NDocumentoBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumentoBuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarKeyPressed

    private void NDocumentoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumentoBuscarKeyReleased

        if (BuscarCliente.isSelected()) {
            int indicado[] ={1,2,3,7,10};
           bd. BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Cliente",
                Boolean.toString(BuscarCliente.isSelected()),TableTipo);
        }else if(BuscarProveedor.isSelected()){
            int indicado[] ={1,2,3,7,8};
            bd.BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Proveedor",
                Boolean.toString(BuscarProveedor.isSelected()),TableTipo);
        }else if(BuscarEmpleado.isSelected()){
            int indicado[] ={1,2,3,7,9};
            bd.BuscarUsuarios( indicado,"`NDocumento` REGEXP '^"+NDocumentoBuscar.getText()+"' AND  Empleado",
                Boolean.toString(BuscarEmpleado.isSelected()),TableTipo);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione el tipo de usuario");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarKeyReleased

    private void NDocumentoBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NDocumentoBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NDocumentoBuscarKeyTyped

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 bd.UsuarioBs( bd.GetTables( TableEmail),"IdUsuario","¿Desea modificarlo?",this);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void BuscarEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEmailFocusGained

    private void BuscarEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEmailFocusLost

    private void BuscarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEmailActionPerformed

    private void BuscarEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEmailKeyPressed

    private void BuscarEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarEmailKeyReleased
        int indicado[] ={1,2,3,7,4};
        bd.BuscarUsuarios( indicado,"Email",BuscarEmail.getText(),TableEmail);
    }//GEN-LAST:event_BuscarEmailKeyReleased

    private void BuscarEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarEmailKeyTyped

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                                    
 bd.UsuarioBs( bd.GetTables( TableBancaria),"IdUsuario","¿Desea modificarlo?",this);    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void NumeroCuentasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumeroCuentasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasFocusGained

    private void NumeroCuentasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumeroCuentasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasFocusLost

    private void NumeroCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasActionPerformed

    private void NumeroCuentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroCuentasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasKeyPressed

    private void NumeroCuentasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroCuentasKeyReleased
        int indicado[] ={1,2,3,5,6};
       bd. BuscarUsuarios( indicado,"NCuentaBancaria",NumeroCuentas.getText(),TableBancaria);        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasKeyReleased

    private void NumeroCuentasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroCuentasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCuentasKeyTyped

    private void NBanco1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NBanco1ItemStateChanged
        int indicado[] ={1,2,3,5,6};
       bd. BuscarUsuarios( indicado,"NombreCuenta",NBanco1.getSelectedItem().toString(),TableBancaria);         // TODO add your handling code here:
    }//GEN-LAST:event_NBanco1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdColumnas","IdUsuario");
        hm1.put("ValorId",idUsuarioBuscar.getText());
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);

//general.Cambiacolor(JPanel[]);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdUsuario",idUsuarioBuscar.getText());
        
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdUsuario",idUsuarioBuscar.getText());
        
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdUsuario",idUsuarioBuscar.getText());
        
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdUsuario",idUsuarioBuscar.getText());
        
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Map hm1 = new HashMap();
   hm1.put("IdUsuario",idUsuarioBuscar.getText());
        
        inf=new Generar_Informes("src\\Informes\\report1.jasper",hm1);
        general.OpenWindows(inf, jPanel2);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarUsuario().setVisible(true);
            }
        });
    }
    GENERAL_CLASS general= new GENERAL_CLASS();
    Generar_Informes inf;
    UserCheck bd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BusNombreUsuario;
    private javax.swing.JRadioButton BuscarCliente;
    private javax.swing.JTextField BuscarEmail;
    private javax.swing.JRadioButton BuscarEmpleado;
    private javax.swing.JRadioButton BuscarProveedor;
    private javax.swing.JPanel BuscarUsuario;
    private javax.swing.JComboBox<String> NBanco1;
    private javax.swing.JTextField NDocumento2;
    private javax.swing.JTextField NDocumentoBuscar;
    private javax.swing.JTextField NumeroCuentas;
    private javax.swing.JTable TableBancaria;
    private javax.swing.JTable TableCodigos;
    private javax.swing.JTable TableDocumento;
    private javax.swing.JTable TableEmail;
    private javax.swing.JTable TableNombre;
    private javax.swing.JTable TableTipo;
    private javax.swing.JTextField idUsuarioBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
