/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CLASES.GENERAL_CLASS;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Edwin
 */
public class Generar_Informes extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int LayoutX;//VARIABLES GLOBALES PARA DESPLAZAR LA VENTANA INFORMES
    int LayoutY;//VARIABLES GLOBALES PARA DESPLAZAR LA VENTANA INFORMES

    public Generar_Informes(String Informe1,Map hm1) {
        initComponents();
          hm =hm1;
          
        Informe = Informe1;
        BTN_REDIMENCIONAR.setEnabled(false);
        BTN_REDIMENCIONAR.setVisible(false);
        jLabel10.setVisible(false);
    }

  

    private Generar_Informes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_informes = new javax.swing.JPanel();
        CABEZERA_VENTANA_INFORMES = new javax.swing.JPanel();
        BTN_CERRAR = new javax.swing.JLabel();
        BTN_MAXIMIZAR = new javax.swing.JLabel();
        BTN_MINIMIZAR = new javax.swing.JLabel();
        BTN_REDIMENCIONAR = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(34, 40, 44));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_informes.setBackground(new java.awt.Color(64, 64, 64));
        jpanel_informes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpanel_informes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpanel_informes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CABEZERA_VENTANA_INFORMES.setBackground(new java.awt.Color(0, 51, 51));
        CABEZERA_VENTANA_INFORMES.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        CABEZERA_VENTANA_INFORMES.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CABEZERA_VENTANA_INFORMESMouseDragged(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CABEZERA_VENTANA_INFORMESMousePressed(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_CERRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cerrar.png"))); // NOI18N
        BTN_CERRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_CERRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_CERRARMouseClicked(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.add(BTN_CERRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 3, -1, -1));

        BTN_MAXIMIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Maximizar.png"))); // NOI18N
        BTN_MAXIMIZAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MAXIMIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MAXIMIZARMouseClicked(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.add(BTN_MAXIMIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 3, -1, -1));

        BTN_MINIMIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Minimizar.png"))); // NOI18N
        BTN_MINIMIZAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_MINIMIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_MINIMIZARMouseClicked(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.add(BTN_MINIMIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 3, -1, -1));

        BTN_REDIMENCIONAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_shrink_24px_1.png"))); // NOI18N
        BTN_REDIMENCIONAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_REDIMENCIONAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_REDIMENCIONARMouseClicked(evt);
            }
        });
        CABEZERA_VENTANA_INFORMES.add(BTN_REDIMENCIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 5, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GENERACIÓN DE INFORMES - VISTA PREVIA / DESCARGA");
        CABEZERA_VENTANA_INFORMES.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jpanel_informes.add(CABEZERA_VENTANA_INFORMES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONE FORMATO DE INFORME");
        jpanel_informes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 410, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PDF");
        jpanel_informes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WORD");
        jpanel_informes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EXCEL");
        jpanel_informes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_microsoft_excel_60px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_pdf_50px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_microsoft_word_60px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 120, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SALIR");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jpanel_informes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jButton1.setBackground(new java.awt.Color(80, 80, 80));
        jButton1.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_analyze_40px.png"))); // NOI18N
        jButton1.setText("  VISTA PREVIA");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpanel_informes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(80, 80, 80));
        jButton2.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_downloads_folder_40px_1.png"))); // NOI18N
        jButton2.setText("  DESCARGAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpanel_informes.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_exit_32px_2.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jpanel_informes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("¿DESEAS SALIR?");
        jpanel_informes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        getContentPane().add(jpanel_informes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_MINIMIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MINIMIZARMouseClicked
        setState(ICONIFIED);//MINIMIZA LA VENTANA PRINCIPAL
    }//GEN-LAST:event_BTN_MINIMIZARMouseClicked

    private void BTN_MAXIMIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_MAXIMIZARMouseClicked
        BTN_REDIMENCIONAR.setEnabled(true);//ACTIVA EL BOTÓN REDIMENCIONAR
        BTN_REDIMENCIONAR.setVisible(true);//MUESTRA EL BOTÓN REDIMENCIONAR
        setExtendedState(MAXIMIZED_BOTH);// MAXIMIZA LA VENTANA PRINCIPAL
        BTN_MAXIMIZAR.setEnabled(false);//DESACTIVA EL BOTÓN MAXIMIZAR
        BTN_MAXIMIZAR.setVisible(false);//OCULTA EL BOTÓN MAXIMIZAR
    }//GEN-LAST:event_BTN_MAXIMIZARMouseClicked

    private void BTN_CERRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_CERRARMouseClicked
        dispose();// CIERRA LA VENTANA
    }//GEN-LAST:event_BTN_CERRARMouseClicked

    private void BTN_REDIMENCIONARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_REDIMENCIONARMouseClicked
        Dimension d = new Dimension(600, 400);//REDIMENSIONA LA VENTANA
        this.setSize(d);//PARTE DE LA ACCIÓN DE REDIMENSIONAR
        this.setLocationRelativeTo(null);//CENTRA LA VENTANA
        BTN_REDIMENCIONAR.setEnabled(false);//DESACTIVA EL BOTÓN REDIMENCIONAR
        BTN_REDIMENCIONAR.setVisible(false);//OCULTA EL BOTÓN REDIMENCIONAR
        BTN_MAXIMIZAR.setEnabled(true);//ACTIVA EL BOTÓN MAXIMIZAR
        BTN_MAXIMIZAR.setVisible(true);//MUESTRA EL BOTÓN MAXIMIZAR

    }//GEN-LAST:event_BTN_REDIMENCIONARMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();// CIERRA LA VENTANA
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        dispose();// CIERRA LA VENTANA
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel10.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel10.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jLabel10.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel10.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseExited

    private void CABEZERA_VENTANA_INFORMESMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CABEZERA_VENTANA_INFORMESMousePressed
        // CUANDO MANTENGA PRESIONADO EL MOUSE EN LA CABEZERA DE LA VENTANA INFORMES
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1)//
        {
            LayoutX = evt.getX();
            LayoutY = evt.getY();
        }
        
    }//GEN-LAST:event_CABEZERA_VENTANA_INFORMESMousePressed

    private void CABEZERA_VENTANA_INFORMESMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CABEZERA_VENTANA_INFORMESMouseDragged
        // TODO add your handling code here:
        {
            this.setLocation(evt.getXOnScreen()-LayoutX,evt.getYOnScreen()-LayoutY);
        }
    }//GEN-LAST:event_CABEZERA_VENTANA_INFORMESMouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //general.Informes(Informe,hm);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generar_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generar_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generar_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generar_Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generar_Informes().setVisible(true);
            }
        });
    }
    Map hm;
    String Informe;
GENERAL_CLASS general = new GENERAL_CLASS();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTN_CERRAR;
    private javax.swing.JLabel BTN_MAXIMIZAR;
    private javax.swing.JLabel BTN_MINIMIZAR;
    private javax.swing.JLabel BTN_REDIMENCIONAR;
    private javax.swing.JPanel CABEZERA_VENTANA_INFORMES;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel jpanel_informes;
    // End of variables declaration//GEN-END:variables
}
