/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CLASES.GENERAL_CLASS;
import CLASES.MySQL_Query;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAVIER
 */
public class UserCheck extends javax.swing.JFrame {

    /**
     *
     * Creates new form Proveedores
     */
    public UserCheck(MySQL_Query BodegasInicio, boolean ini) {
        initComponents();
        Querys = BodegasInicio;
        ini = inic;
        //Pruebas
        activa(inic);
        //Pruebas3
        Auxili(ini);
        JTextField TextUB1[] = {Nombre_Completo, CodInterno};
        JTextField TextProveedor1[] = {EnlaceWeb};
        TextUB = TextUB1;
        TextProveedor = TextProveedor1;
        JPanel PanelInternos1[];
        JTextField TextBox1[];
        JPanel PanelFondos1[];
        JLabel Text1[]={jLabel58,jLabel51,jLabel54,jLabel53,jLabel3,jLabel45,jLabel47,
jLabel59,jLabel60,jLabel61,jLabel62,jLabel34,jLabel36,jLabel35};
        Text=Text1;

    }
    String[] botonestuto = {"<html><p style = \"font:14px\">SIGUIENTE</html></p>", "<html><p style = \"font:14px\">ATRAS</html></p>"}; //BOTONES DE TUTORIAL
    //String[] botonestutorial = {"<html><p style = \"font:14px\">SIGUIENTE</html></p>", "<html><p style = \"font:14px\">ATRAS</html></p>"}; //BOTONES DE TUTORIAL

    public UserCheck() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Auxili(Boolean x) {
        TableAux.setEnabled(x);
        PanelAxuliar.setEnabled(x);
//pruebas
    }

    public void activa(Boolean x) {
        Nombre_Completo.setEnabled(x);
        NumeroCelular.setEnabled(x);
        if (x == false) {
            PaneUsuario.setEnabled(x);
            Aux.setSelected(false);
            User.setSelected(false);
        }

        Aux.setEnabled(x);
        User.setEnabled(x);

        btGuardar.setEnabled(x);
        btAdicionar.setVisible(!x);

        btCancelar.setVisible(x);
        btActualizar.setVisible(x);

        btModificar.setVisible(x);
        //   PanelProveedor.setVisible(x);
    }

    public void LimbiarUB() {

        activa(false);

        btActualizar.setSelected(false);
        btModificar.setSelected(false);
        Icon Imagenes = new ImageIcon(getClass().getResource("/IMAGENES/Usuario5.png"));
        jLabel1.setIcon(Imagenes);
    }

    private void LimpiarPro() {
        Object text[] = {TableAux};
        general.LimpiarTodo(text);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        TipoUsuario = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        CrearUsuarioPanel = new javax.swing.JPanel();
        PaneUsuario = new javax.swing.JTabbedPane();
        PanelAxuliar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAux = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        Usuario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DatosProveedor = new javax.swing.JPanel();
        DepCorta23 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        DepCorta24 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        Diametro = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        EnlaceWeb = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        Lontxt = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        LatitudTxt = new javax.swing.JTextField();
        Ruta = new javax.swing.JComboBox<>();
        Cliclo = new javax.swing.JComboBox<>();
        CodInterno = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Aux = new javax.swing.JCheckBox();
        User = new javax.swing.JCheckBox();
        Nombre_Completo = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btModificar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CODIGOS = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        NumeroCelular = new javax.swing.JTextField();
        BTN_TUTORIAL = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearUsuarioPanel.setBackground(new java.awt.Color(18, 21, 38));
        CrearUsuarioPanel.setPreferredSize(new java.awt.Dimension(740, 640));
        CrearUsuarioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneUsuario.setBackground(new java.awt.Color(51, 153, 255));
        PaneUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PaneUsuario.setFocusable(false);
        PaneUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PaneUsuario.setMinimumSize(new java.awt.Dimension(303, 26));

        PanelAxuliar.setBackground(new java.awt.Color(16, 34, 43));
        PanelAxuliar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AUXILIARES");
        PanelAxuliar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 30));

        TableAux.setBackground(new java.awt.Color(16, 34, 43));
        TableAux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(TableAux);

        PanelAxuliar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 620, 250));

        PaneUsuario.addTab("AUXILIARES", PanelAxuliar);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setBackground(new java.awt.Color(16, 34, 43));
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USUARIOS");
        Usuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, -1));
        Usuario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 10));

        jPanel5.setBackground(new java.awt.Color(16, 34, 43));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Usuario5.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 136, -1));

        Usuario.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 190, 140));

        DatosProveedor.setBackground(new java.awt.Color(16, 34, 43));
        DatosProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Medidor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        DatosProveedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DepCorta23.setBackground(new java.awt.Color(16, 34, 43));
        DepCorta23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DepCorta23.setForeground(new java.awt.Color(255, 255, 255));
        DepCorta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepCorta23ActionPerformed(evt);
            }
        });
        DatosProveedor.add(DepCorta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Marca");
        DatosProveedor.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Diametro");
        DatosProveedor.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        DepCorta24.setBackground(new java.awt.Color(16, 34, 43));
        DepCorta24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DepCorta24.setForeground(new java.awt.Color(255, 255, 255));
        DepCorta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepCorta24ActionPerformed(evt);
            }
        });
        DatosProveedor.add(DepCorta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Tipo");
        DatosProveedor.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        Diametro.setBackground(new java.awt.Color(16, 34, 43));
        Diametro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Diametro.setForeground(new java.awt.Color(255, 255, 255));
        Diametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INNACTIVO", "REPORTADO" }));
        org.jdesktop.swingx.autocomplete.AutoCompleteDecorator.decorate(Diametro);
        Diametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiametroActionPerformed(evt);
            }
        });
        DatosProveedor.add(Diametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, 30));

        Usuario.add(DatosProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 330, 160));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Codigo Interno");
        Usuario.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Ciclo");
        Usuario.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 20));

        EnlaceWeb.setBackground(new java.awt.Color(16, 34, 43));
        EnlaceWeb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EnlaceWeb.setForeground(new java.awt.Color(255, 255, 255));
        EnlaceWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnlaceWebActionPerformed(evt);
            }
        });
        Usuario.add(EnlaceWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 30));

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Ruta");
        Usuario.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Enlace Web");
        Usuario.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 20));

        Lontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LontxtActionPerformed(evt);
            }
        });
        Usuario.add(Lontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 30));

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Longitud");
        Usuario.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Latitud");
        Usuario.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 20));

        LatitudTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatitudTxtActionPerformed(evt);
            }
        });
        Usuario.add(LatitudTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 140, 30));

        Ruta.setBackground(new java.awt.Color(16, 34, 43));
        Ruta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Ruta.setForeground(new java.awt.Color(255, 255, 255));
        Ruta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INNACTIVO", "REPORTADO" }));
        org.jdesktop.swingx.autocomplete.AutoCompleteDecorator.decorate(Diametro);
        Ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaActionPerformed(evt);
            }
        });
        Usuario.add(Ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 30));

        Cliclo.setBackground(new java.awt.Color(16, 34, 43));
        Cliclo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cliclo.setForeground(new java.awt.Color(255, 255, 255));
        Cliclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INNACTIVO", "REPORTADO" }));
        org.jdesktop.swingx.autocomplete.AutoCompleteDecorator.decorate(Diametro);
        Cliclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClicloActionPerformed(evt);
            }
        });
        Usuario.add(Cliclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, 30));

        CodInterno.setBackground(new java.awt.Color(16, 34, 43));
        CodInterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CodInterno.setForeground(new java.awt.Color(255, 255, 255));
        CodInterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CodInternoFocusGained(evt);
            }
        });
        CodInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodInternoActionPerformed(evt);
            }
        });
        Usuario.add(CodInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));

        jPanel13.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 330));

        PaneUsuario.addTab("USUARIOS", jPanel13);

        CrearUsuarioPanel.add(PaneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 360));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("NÚMERO DE CELULAR");
        CrearUsuarioPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("NOMBRE COMPLETO");
        CrearUsuarioPanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Aux.setBackground(new java.awt.Color(255, 255, 255));
        TipoUsuario.add(Aux);
        Aux.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Aux.setForeground(new java.awt.Color(255, 255, 255));
        Aux.setText("AUXILIAR");
        Aux.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Aux.setOpaque(false);
        Aux.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AuxItemStateChanged(evt);
            }
        });
        Aux.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AuxStateChanged(evt);
            }
        });
        CrearUsuarioPanel.add(Aux, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 110, 30));

        User.setBackground(new java.awt.Color(255, 255, 255));
        TipoUsuario.add(User);
        User.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("USUARIO");
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        User.setOpaque(false);
        User.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UserItemStateChanged(evt);
            }
        });
        CrearUsuarioPanel.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        Nombre_Completo.setBackground(new java.awt.Color(16, 34, 43));
        Nombre_Completo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nombre_Completo.setForeground(new java.awt.Color(255, 255, 255));
        Nombre_Completo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Nombre_CompletoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Nombre_CompletoFocusLost(evt);
            }
        });
        Nombre_Completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_CompletoActionPerformed(evt);
            }
        });
        Nombre_Completo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nombre_CompletoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Nombre_CompletoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nombre_CompletoKeyTyped(evt);
            }
        });
        CrearUsuarioPanel.add(Nombre_Completo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 300, 30));

        btAdicionar.setBackground(new java.awt.Color(16, 34, 43));
        btAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Agregar.png"))); // NOI18N
        btAdicionar.setText("ADICIONAR");
        btAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        btAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btAdicionarKeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 150, 50));

        btModificar.setBackground(new java.awt.Color(16, 34, 43));
        btModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btModificar.setForeground(new java.awt.Color(255, 255, 255));
        btModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Modificar.png"))); // NOI18N
        btModificar.setText("INFORME");
        btModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });
        btModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btModificarKeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 50));

        btGuardar.setBackground(new java.awt.Color(16, 34, 43));
        btGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Guardar.png"))); // NOI18N
        btGuardar.setText("GUARDAR");
        btGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        btGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btGuardarKeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 140, 50));

        btActualizar.setBackground(new java.awt.Color(16, 34, 43));
        btActualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Actualizar.png"))); // NOI18N
        btActualizar.setText("ACTUALIZAR");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });
        btActualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btActualizarKeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 150, 50));

        btCancelar.setBackground(new java.awt.Color(16, 34, 43));
        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Cancelar.png"))); // NOI18N
        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        btCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btCancelarKeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 150, 50));

        btModificar1.setBackground(new java.awt.Color(16, 34, 43));
        btModificar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btModificar1.setForeground(new java.awt.Color(255, 255, 255));
        btModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Buscar.png"))); // NOI18N
        btModificar1.setText("BUSCAR");
        btModificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificar1ActionPerformed(evt);
            }
        });
        btModificar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btModificar1KeyReleased(evt);
            }
        });
        CrearUsuarioPanel.add(btModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 140, 50));

        jPanel1.setBackground(new java.awt.Color(12, 14, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CODIGOS.setBackground(new java.awt.Color(16, 34, 43));
        CODIGOS.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CODIGOS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CODIGOS.setEnabled(false);
        CODIGOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODIGOSActionPerformed(evt);
            }
        });
        jPanel1.add(CODIGOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 200, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("CREAR USUARIO");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Código");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        CrearUsuarioPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        NumeroCelular.setBackground(new java.awt.Color(16, 34, 43));
        NumeroCelular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NumeroCelular.setForeground(new java.awt.Color(255, 255, 255));
        NumeroCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumeroCelularFocusGained(evt);
            }
        });
        NumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroCelularActionPerformed(evt);
            }
        });
        CrearUsuarioPanel.add(NumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 300, 30));

        BTN_TUTORIAL.setBackground(new java.awt.Color(16, 34, 43));
        BTN_TUTORIAL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTN_TUTORIAL.setForeground(new java.awt.Color(255, 255, 255));
        BTN_TUTORIAL.setText("TUTORIAL");
        BTN_TUTORIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_TUTORIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TUTORIALActionPerformed(evt);
            }
        });
        CrearUsuarioPanel.add(BTN_TUTORIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jPanel2.add(CrearUsuarioPanel);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void Nombre_CompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_CompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_CompletoActionPerformed

    private void CodInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodInternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodInternoActionPerformed

    private void CODIGOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODIGOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODIGOSActionPerformed

    private void idProveedor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProveedor9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProveedor9ActionPerformed

    private void DepCorta35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta35ActionPerformed

    private void DepCorta34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta34ActionPerformed

    private void DepCorta33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta33ActionPerformed

    private void DepCorta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta32ActionPerformed

    private void DepCorta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta31ActionPerformed

    private void DepCorta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta21ActionPerformed

    private void DepCorta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta20ActionPerformed

    private void Adicionar() {
        activa(true);
    }
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
//PanelProveedor.setEnabled(false);  
        Adicionar();
    }//GEN-LAST:event_btAdicionarActionPerformed
    private void Teclas(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 112) {
            Adicionar();
        }
        if (evt.getKeyCode() == 112) {
            Actualizar();
        }
        if (evt.getKeyCode() == 112) {
            Informe();
        }
        if (evt.getKeyCode() == 112) {
            Guardar();
        }
        if (evt.getKeyCode() == 112) {
            Cancelar();
        }
        if (evt.getKeyCode() == 112) {
            Buscar();
        }

    }
    private void btAdicionarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAdicionarKeyReleased
        Teclas(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarKeyReleased
    private void Informe() {
        Map hm1 = new HashMap();
        hm1.put("IdValor", Nombre_Completo.getText());
        Generar_Informes inf = new Generar_Informes("src\\Informes\\report2.jasper", hm1);
        general.OpenWindows(inf, null);

    }
    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        Informe();
    }//GEN-LAST:event_btModificarActionPerformed
    //Insertar Proveedor a Mysql 
    public void DatosProveedor() {
        //  RazonSocialNom = Cliclo.getText();
        idCodigoInterno = CodInterno.getText();
        //   Tel =Ruta.getText();
        EnlaceWEB = EnlaceWeb.getText();

        id = CODIGOS.getText();
    }

    private void ProovedoresMySQL() {
        DatosProveedor();
//                    Querys.InsertarProveedor(IdCliclo, idCodigoInterno, idRuta, EnlaceWEB, ResponsableIVA, AutoRetenedor, id);   

    }

    private void EmpleadoMySQL() {
        System.out.print("Ingresado Empleado ");
    }

    private void ClienteMySQL() {
        System.out.print("Ingresado Empleado ");

    }

    //Valirdar Check de Proveedor 
    private void InsertarUsuario() {

        boolean ValidarVacioPRO = general.VaciosText(TextProveedor);
        boolean ValidarVacioEm = true;
        boolean ValidarVacioCli = true;

        // Proveedor
        if (!User.isSelected() && Aux.isSelected()) {
            if (ValidarVacioPRO) {
                InsertarUsuarioBasicoMysql();
                ProovedoresMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }
        }
        //Empleado 
        if (User.isSelected() && !Aux.isSelected()) {
            if (ValidarVacioEm) {
                InsertarUsuarioBasicoMysql();
                EmpleadoMySQL();
                LimbiarUB();

            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }
        }
        //Cliente
        if (!User.isSelected() && !Aux.isSelected()) {
            if (ValidarVacioCli) {
                InsertarUsuarioBasicoMysql();
                ClienteMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }

        }

        //Todos Empleado cliente y proveedor
        if (User.isSelected() && Aux.isSelected()) {

            if (ValidarVacioPRO && ValidarVacioCli && ValidarVacioEm) {
                InsertarUsuarioBasicoMysql();
                EmpleadoMySQL();
                ProovedoresMySQL();
                ClienteMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }

        }
        //Cliente 
        if (!User.isSelected() && Aux.isSelected()) {
            if (ValidarVacioPRO && ValidarVacioCli) {
                InsertarUsuarioBasicoMysql();
                ProovedoresMySQL();
                ClienteMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }

        }
        //Empleado y cliente
        if (User.isSelected() && !Aux.isSelected()) {
            if (ValidarVacioEm && ValidarVacioCli) {
                InsertarUsuarioBasicoMysql();
                EmpleadoMySQL();
                ClienteMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }

        }
        //Empleado y proveedor
        if (User.isSelected() && Aux.isSelected()) {
            if (ValidarVacioPRO && ValidarVacioEm) {
                InsertarUsuarioBasicoMysql();
                EmpleadoMySQL();
                ProovedoresMySQL();
                LimbiarUB();
            } else {
                JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Proveedor");
            }
        }

    }

    public boolean ValirdarBancos() {
        boolean Valir = false;

        return Valir;
    }

    private void InsertarUsuarioBasicoMysql() {
        GetTextUsuarioBD();
        //    Querys.InsertarUsuarioBC(id,TipoDoc, NumeroDocumento, NombreCompleto, Emailusuario,NCuentaBancaria , NombreBanco, Estado, ChecKPro, ChecKPro, ChecKEm,CheakBanco,ChecKCorriente,ChecKAhorro,imagen);

    }
    private void btModificarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btModificarKeyReleased
        Teclas(evt);             // TODO add your handling code here:
    }//GEN-LAST:event_btModificarKeyReleased
    private void Guardar() {
        boolean ValidarVacioUB = general.VaciosText(TextUB);
        boolean ValirdarVacioUBC = general.VaciosCombobox(ComboboxUB);

        if (ValidarVacioUB && ValirdarVacioUBC && ValirdarBancos()) {
            if (Aux.isSelected() || User.isSelected()) {
                InsertarUsuario();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar un tipo de Usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llenar todos los datos de datos Usuario Basicos");
        }

    }
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        Guardar();

    }//GEN-LAST:event_btGuardarActionPerformed

    private void btGuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarKeyReleased
        Teclas(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarKeyReleased
    public void ModificarProveedor() {

        DatosProveedor();
        //   Querys.ModicarProveedor(IdCliclo, idCodigoInterno, idRuta, EnlaceWEB, ResponsableIVA, AutoRetenedor, id);   
    }

//Funcion Para modificar los datos Basicos de Usuario
    public void GetTextUsuarioBD() {
        AuxCheck = Aux.isSelected();

        ChecKEm = User.isSelected();

        NombreCompleto = Nombre_Completo.getText();
        idCodigoInterno = CodInterno.getText();

        id = CODIGOS.getText();

    }

    public void ModificarUsuarioBD() {
        GetTextUsuarioBD();
        //     Querys.ModificarUsuarioBD(TipoDoc, NumeroDocumento, NombreCompleto, Emailusuario,NCuentaBancaria , NombreBanco, Estado, ChecKPro,ChecKPro, ChecKEm,id,CheakBanco,ChecKCorriente,ChecKAhorro,imagen);
    }

    private void Actualizar() {
        try {
            ModificarUsuarioBD();
            ModificarProveedor();
            activa(false);
            LimbiarUB();
            btGuardar.setVisible(true);
        } catch (Exception ex) {
        }

    }
    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        Actualizar();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btActualizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btActualizarKeyReleased
        Teclas(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_btActualizarKeyReleased
    private void Cancelar() {

        int conf = general.ValdarCerrar();
        if (conf == 0) {
            LimbiarUB();
            activa(false);
            btGuardar.setVisible(true);

        }
    }
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed

        Cancelar();


    }//GEN-LAST:event_btCancelarActionPerformed

    private void btCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btCancelarKeyReleased
        Teclas(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarKeyReleased

    private void AuxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AuxItemStateChanged
        Boolean ac = Aux.isSelected();
        if (ac) {
            Auxili(ac);
            ActivarUsuario(!ac);
            PaneUsuario.setEnabled(ac);
            PaneUsuario.setSelectedIndex(0);
        } else {
            PaneUsuario.setEnabled(ac);
            ActivarUsuario(!ac);
            Auxili(ac);
            LimpiarPro();
        }
        //ProveedoreAction(true);
        //System.out.println("  action  ");      // TODO add your handling code here:
    }//GEN-LAST:event_AuxItemStateChanged
    public void ActivarUsuario(boolean as) {
        Usuario.setEnabled(as);
        CodInterno.setEnabled(as);
        Cliclo.setEnabled(as);
        Ruta.setEnabled(as);
        EnlaceWeb.setEnabled(as);
        Lontxt.setEnabled(as);
        LatitudTxt.setEnabled(as);
        DatosProveedor.setEnabled(as);
        Lontxt.setEnabled(as);
        LatitudTxt.setEnabled(as);
        Usuario.setEnabled(as);
    }

    ;

    private void UserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UserItemStateChanged
        boolean as = User.isSelected();
        PaneUsuario.setSelectedIndex(1);
        if (as) {
            PaneUsuario.setEnabled(as);
            Auxili(!as);
            ActivarUsuario(as);
        } else {
            PaneUsuario.setEnabled(as);
            Auxili(!as);
            ActivarUsuario(as);

        }
    }//GEN-LAST:event_UserItemStateChanged
    private void Buscar() {
        general.OpenWindows(usuario, null);

    }
    private void btModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificar1ActionPerformed
        Buscar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btModificar1ActionPerformed

    private void btModificar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btModificar1KeyReleased
        Teclas(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_btModificar1KeyReleased

    private void AuxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AuxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_AuxStateChanged

    private void TipoDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoDocumentoMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoMousePressed

    private void TipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TipoDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoMouseClicked

    private void TipoDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TipoDocumentoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoFocusLost

    private void TipoDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TipoDocumentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoFocusGained

    private void TipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TipoDocumentoItemStateChanged
//        System.out.println("s");        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoItemStateChanged

    private void TipoDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TipoDocumentoKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoKeyPressed

    private void TipoDocumentoHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_TipoDocumentoHierarchyChanged

// TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoHierarchyChanged
    public void BuscarUser(ResultSet resultado) {
        try {
            //Usuario Basico
            CODIGOS.setText(resultado.getString(1));
            Nombre_Completo.setText(resultado.getString(2));

            CodInterno.setText(resultado.getString(4));

            Aux.setSelected(resultado.getBoolean(9));
            User.setSelected(resultado.getBoolean(10));

            //PROVEEDOR
            //    Cliclo.setText(resultado.getString(15));
            CodInterno.setText(resultado.getString(16));
            //    Ruta.setText(resultado.getString(17));
            EnlaceWeb.setText(resultado.getString(18));

            //Imagenes
            general.InsertarImagenLabel(resultado.getBytes(21), jLabel1);

            //EMPLEADO
            //
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }
    private void Nombre_CompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nombre_CompletoFocusLost
        ResultSet resultado = Querys.InicioUsuario();
        String valorMysql = null;
        String ValorInicial = CODIGOS.getText();
        try {
            while (resultado.next()) {
                valorMysql = resultado.getString(1);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        if (valorMysql == ValorInicial) {

        }
        UsuarioBs(Nombre_Completo.getText(), "NDocumento", "Este usuario ya fue creado en la BD,¿Desea Modificarlo?", null);

    }//GEN-LAST:event_Nombre_CompletoFocusLost

    private void Nombre_CompletoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nombre_CompletoFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_CompletoFocusGained

    private void CodInternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodInternoFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_CodInternoFocusGained

    private void Nombre_CompletoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_CompletoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_CompletoKeyReleased

    private void Nombre_CompletoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_CompletoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_CompletoKeyPressed

    private void Nombre_CompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre_CompletoKeyTyped
        general.SoloNumeros(evt, jPanel1);
    }//GEN-LAST:event_Nombre_CompletoKeyTyped
    public void BuscarUsuarios(int indicado[], String Indicador, String GetText, JTable Table) {
        try {
            // ResultSet   rs =Querys.BuscarUsuario("IdUsuario",idUsuarioBuscar.getText() );
            ResultSet rs = Querys.BuscarUsuario(Indicador, GetText);
            general.AgregarTable(Table, indicado, rs);
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(UserCheck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String GetTables(JTable table) {
        String Resultado = "";
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) table.getModel();
        int Rows = table.getSelectedRow();
        Resultado = modelo.getValueAt(Rows, 0).toString();
        return Resultado;
    }

    public void UsuarioBs(String IdUsuario, String Where, String Mensaje, JFrame BuscarUsuario) {
        String Idusuario = IdUsuario;
        try {
            ResultSet resultado = Querys.UsuarioDocBC(Idusuario, Where);
            if (resultado.next()) {
                int conf = JOptionPane.showConfirmDialog(null, Mensaje,
                        "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (conf == 0) {
                    activa(true);
                    btGuardar.setVisible(false);
                    BuscarUser(resultado);
                    BuscarUsuario.setVisible(false);

                } else {
                    activa(false);
                    btGuardar.setVisible(true);

                    LimbiarUB();
                }
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        try {
            //imagen =general.AgregarImagenBit(general.Exan(jPanel1)).toString();
            imagen = general.AgregarImagenBit(general.Exan(CrearUsuarioPanel));
            general.InsertarImagenLabel(imagen, jLabel1);
        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            //imagen =general.AgregarImagenBit(general.Exan(jPanel1)).toString();
            imagen = general.AgregarImagenBit(general.Exan(CrearUsuarioPanel));
            general.InsertarImagenLabel(imagen, jLabel1);
        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void EnlaceWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnlaceWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnlaceWebActionPerformed

    private void DepCorta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta24ActionPerformed

    private void DepCorta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepCorta23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepCorta23ActionPerformed

    private void LontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LontxtActionPerformed

    private void LatitudTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatitudTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudTxtActionPerformed

    private void RutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaActionPerformed

    private void DiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiametroActionPerformed

    private void ClicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClicloActionPerformed

    private void NumeroCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumeroCelularFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCelularFocusGained

    private void NumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroCelularActionPerformed

    private void BTN_TUTORIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TUTORIALActionPerformed
/*        int x = JOptionPane.showOptionDialog(this, "<html><p style = \"font:20px\">Oprime (ADICIONAR)</p></html>", "Tutorial", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, botonestuto, botonestuto[0]);//

        if (x == 0) { //SIGUIENTE
            JOptionPane.showMessageDialog(this, "<html><p style = \"font:20px\">Selecciona (AUXILIAR O USUARIO)</p></html>");

        } else if (x == 1) { //NO
            JOptionPane.showMessageDialog(this, "<html><p style = \"font:20px\">Selecciona (AUXILIAR O USUARIO)</p></html>");
        }
            
        */
        try {
     //       general.ModoDia(Text, null,null, null, null, null, null);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_BTN_TUTORIALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCheck().setVisible(true);
            }
        });

        /*String Documento = NDocumento.getText();
      if (TipoDocumento.getSelectedIndex() !=0 && Documento.length()==0 ) {
                TipoDocumento.setSelectedIndex(0);
        }else{
              int conf = JOptionPane.showConfirmDialog(null, "¿Este usuario ya fue creado, desea modificarlo?", 
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
              System.out.println(conf);
        }*/
        System.out.println(" algo");
    }
    //Se 
    public  JPanel PanelInternos [];
    public  JTextField TextBox[];
    public JPanel PanelFondos[];
    public  JLabel Text[];
    private byte[] imagen = null;
    // Boolean CheakBanco ;
    //  Boolean ChecKAhorro ;
    // Boolean ChecKCorriente;
    String IdCliclo;
    String idCodigoInterno;
    String idRuta;
    String EnlaceWEB;
    //boolean ResponsableIVA ;
    // boolean AutoRetenedor;
    Boolean AuxCheck;

    Boolean ChecKEm;

    String NombreCompleto;
    //  String Emailusuario;
    //  String NombreBanco ;
    //  String NCuentaBancaria ;
    //  String Estado ;
    String id;
    BuscarUsuario usuario = new BuscarUsuario(this);
    public MySQL_Query Querys;
    private boolean inic = false;
    private GENERAL_CLASS general = new GENERAL_CLASS();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Aux;
    private javax.swing.JButton BTN_TUTORIAL;
    private javax.swing.JTextField CODIGOS;
    private javax.swing.JComboBox<String> Cliclo;
    private javax.swing.JTextField CodInterno;
    public javax.swing.JPanel CrearUsuarioPanel;
    private javax.swing.JPanel DatosProveedor;
    private javax.swing.JTextField DepCorta23;
    private javax.swing.JTextField DepCorta24;
    private javax.swing.JComboBox<String> Diametro;
    private javax.swing.JTextField EnlaceWeb;
    private javax.swing.JTextField LatitudTxt;
    private javax.swing.JTextField Lontxt;
    private javax.swing.JTextField Nombre_Completo;
    private javax.swing.JTextField NumeroCelular;
    private javax.swing.JTabbedPane PaneUsuario;
    private javax.swing.JPanel PanelAxuliar;
    private javax.swing.JComboBox<String> Ruta;
    private javax.swing.JTable TableAux;
    private javax.swing.ButtonGroup TipoUsuario;
    private javax.swing.JCheckBox User;
    private javax.swing.JPanel Usuario;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btModificar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
    private JTextField TextEm[];
    private JComboBox ComboboxUB[];
    private JTextField TextUB[];
    private JTextField TextProveedor[];
}
