/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import java.applet.AudioClip;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Edwin
 */
public class AGREGAR_USUARIOS extends javax.swing.JPanel {

    /**
     * Creates new form AGREGAR_USUARIOS
     */
    public AGREGAR_USUARIOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MarcaMedidor = new javax.swing.JTextField();
        Diametro = new javax.swing.JTextField();
        TipoMedidor = new javax.swing.JComboBox<>();
        BTN_GUARDAR_USUARIO = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NombreUsuario = new javax.swing.JTextField();
        CodigRuta = new javax.swing.JTextField();
        CodigInterno = new javax.swing.JTextField();
        Contenedor_QR = new javax.swing.JPanel();
        LBL_QR = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EnlaceUbicacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TelefonoUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("AGREGAR USUARIO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 380, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserte Datos del Usuario", 0, 0, new java.awt.Font("Century Gothic", 0, 18))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("NOMBRE COMPLETO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO DE RUTA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("ENLACE DE UBICACIÓN:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Medidor", 0, 0, new java.awt.Font("Century Gothic", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("MARCA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("DIAMETRO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("TIPO:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        MarcaMedidor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(MarcaMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, -1));

        Diametro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(Diametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, -1));

        TipoMedidor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TipoMedidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VOLUMETRICO", "CHORRO" }));
        jPanel2.add(TipoMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 210, -1));

        BTN_GUARDAR_USUARIO.setBackground(new java.awt.Color(102, 102, 102));
        BTN_GUARDAR_USUARIO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BTN_GUARDAR_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTN_GUARDAR_USUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_save_70px.png"))); // NOI18N
        BTN_GUARDAR_USUARIO.setText("GUARDAR");
        BTN_GUARDAR_USUARIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_GUARDAR_USUARIO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTN_GUARDAR_USUARIO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTN_GUARDAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GUARDAR_USUARIOActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_GUARDAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 140));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_erase_50px.png"))); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 100, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 590, 200));

        NombreUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 200, -1));

        CodigRuta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(CodigRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        CodigInterno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(CodigInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, -1));

        Contenedor_QR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBL_QR.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        LBL_QR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_QR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2locacion_128x128.png"))); // NOI18N
        Contenedor_QR.add(LBL_QR, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 190, 200));

        jPanel1.add(Contenedor_QR, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 50, 200, 200));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("QR DE UBICACIÓN GENERADO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("CODIGO INTERNO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        EnlaceUbicacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        EnlaceUbicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EnlaceUbicacionKeyReleased(evt);
            }
        });
        jPanel1.add(EnlaceUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 200, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("TELEFONO CELULAR:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        TelefonoUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(TelefonoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 630, 490));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 370, 20));

        jPanel3.setBackground(new java.awt.Color(60, 63, 65,80));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 733, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_GUARDAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GUARDAR_USUARIOActionPerformed
        try{
                
                int size = 400;
                    ByteArrayOutputStream out = QRCode.from(this.EnlaceUbicacion.getText()).withSize(220, 220).to(ImageType.JPG).stream();
                    ImageIcon imageIcon = new ImageIcon(out.toByteArray());
                    this.LBL_QR.setIcon(imageIcon);
                }catch(Exception ex){JOptionPane.showMessageDialog(null, "Error Al ingresar "+ ex.getMessage());}
    


    }//GEN-LAST:event_BTN_GUARDAR_USUARIOActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MarcaMedidor.setText("");
        MarcaMedidor.setForeground(Color.BLACK);
        Diametro.setText("");
        Diametro.setForeground(Color.BLACK);
        NombreUsuario.setText("");
        NombreUsuario.setForeground(Color.BLACK);
        CodigRuta.setText("");
        CodigRuta.setForeground(Color.BLACK);
        TelefonoUsuario.setText("");
        TelefonoUsuario.setForeground(Color.BLACK);
        CodigInterno.setText("");
        CodigInterno.setForeground(Color.BLACK);
        EnlaceUbicacion.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnlaceUbicacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnlaceUbicacionKeyReleased
        int size = 400;
        ByteArrayOutputStream out = QRCode.from(this.EnlaceUbicacion.getText()).withSize(220, 220).to(ImageType.JPG).stream();
        ImageIcon imageIcon = new ImageIcon(out.toByteArray());
        this.LBL_QR.setIcon(imageIcon);
    }//GEN-LAST:event_EnlaceUbicacionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_GUARDAR_USUARIO;
    private javax.swing.JTextField CodigInterno;
    private javax.swing.JTextField CodigRuta;
    private javax.swing.JPanel Contenedor_QR;
    private javax.swing.JTextField Diametro;
    private javax.swing.JTextField EnlaceUbicacion;
    private javax.swing.JLabel LBL_QR;
    private javax.swing.JTextField MarcaMedidor;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JTextField TelefonoUsuario;
    private javax.swing.JComboBox<String> TipoMedidor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
