/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catastro;


public class B_Inicio extends javax.swing.JFrame {

    

    /**
     * Creates new form B_Inicio
     */
    //PANEL DE USUARIOS
 

    public B_Inicio() {

        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ITEM_CICLOS = new javax.swing.JMenuItem();
        ITEMA_CHAT_BOT = new javax.swing.JMenuItem();
        ITEM_USUARIOS = new javax.swing.JMenuItem();
        ITEM_POSICION = new javax.swing.JMenuItem();
        ITEM_ESTADISTICOS = new javax.swing.JMenuItem();
        ITEM_INFORMES = new javax.swing.JMenuItem();
        ITEM_MENU = new javax.swing.JMenuItem();
        COPIAR = new javax.swing.JMenuItem();
        PEGAR = new javax.swing.JMenuItem();
        MODO_DIA = new javax.swing.JMenuItem();
        MODO_NOCHE = new javax.swing.JMenuItem();
        pnlRoot = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        Menu_Lateral_Derecho = new javax.swing.JPanel();
        Panel_Central_Cambiable = new javax.swing.JPanel();
        Panel_Degradado = new org.netbeans.modules.form.InvalidComponent();
        TXT_CICLOS = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        TXT_BOT = new javax.swing.JLabel();
        TXT_USER = new javax.swing.JLabel();
        TXT_POSICION = new javax.swing.JLabel();
        TXT_GRAFICOS = new javax.swing.JLabel();
        TXT_INFORMES = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        TXT_LICENCIA = new javax.swing.JLabel();

        ITEM_CICLOS.setText("CICLOS               \"F1\"");
        ITEM_CICLOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_CICLOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_CICLOSActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_CICLOS);

        ITEMA_CHAT_BOT.setText("CHAT BOT          \"F2\"");
        ITEMA_CHAT_BOT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEMA_CHAT_BOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMA_CHAT_BOTActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEMA_CHAT_BOT);

        ITEM_USUARIOS.setText("USUARIOS          \"F3\"");
        ITEM_USUARIOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_USUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_USUARIOSActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_USUARIOS);

        ITEM_POSICION.setText("POSICIÓN           \"F4\"");
        ITEM_POSICION.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_POSICION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_POSICIONActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_POSICION);

        ITEM_ESTADISTICOS.setText("ESTADÍSTICOS  \"F5\"");
        ITEM_ESTADISTICOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_ESTADISTICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_ESTADISTICOSActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_ESTADISTICOS);

        ITEM_INFORMES.setText("INFORMES          \"F6\"");
        ITEM_INFORMES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_INFORMES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_INFORMESActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_INFORMES);

        ITEM_MENU.setText("MENÚ                \"ALT+M\"");
        ITEM_MENU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ITEM_MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEM_MENUActionPerformed(evt);
            }
        });
        jPopupMenu1.add(ITEM_MENU);

        COPIAR.setText("Copiar              \"CTRL+C\"");
        COPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPopupMenu1.add(COPIAR);

        PEGAR.setText("Pegar               \"CTRL+V\"");
        PEGAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPopupMenu1.add(PEGAR);

        MODO_DIA.setText("Modo Día         \"ALT+D\"");
        MODO_DIA.setActionCommand("Modo Día  \"ALT+D\"");
        MODO_DIA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MODO_DIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODO_DIAActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MODO_DIA);

        MODO_NOCHE.setText("Modo Noche    \"ALT+N\"");
        MODO_NOCHE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MODO_NOCHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODO_NOCHEActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MODO_NOCHE);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRoot.setComponentPopupMenu(jPopupMenu1);
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlCenter.setBackground(new java.awt.Color(244, 245, 247));
        pnlCenter.setComponentPopupMenu(jPopupMenu1);
        pnlCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCenterMouseClicked(evt);
            }
        });

        Menu_Lateral_Derecho.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout Menu_Lateral_DerechoLayout = new javax.swing.GroupLayout(Menu_Lateral_Derecho);
        Menu_Lateral_Derecho.setLayout(Menu_Lateral_DerechoLayout);
        Menu_Lateral_DerechoLayout.setHorizontalGroup(
            Menu_Lateral_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        Menu_Lateral_DerechoLayout.setVerticalGroup(
            Menu_Lateral_DerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        Panel_Central_Cambiable.setBackground(new java.awt.Color(244, 245, 247));
        Panel_Central_Cambiable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Central_Cambiable.setComponentPopupMenu(jPopupMenu1);
        Panel_Central_Cambiable.setLayout(new java.awt.CardLayout());

        Panel_Degradado.null;
        Panel_Degradado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXT_CICLOS.setForeground(new java.awt.Color(255, 255, 255));
        TXT_CICLOS.setText("CICLOS");
        TXT_CICLOS.setOpaque(true);
        Panel_Degradado.add(TXT_CICLOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(243, 244, 246));
        Panel_Degradado.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, 50, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(243, 244, 246));
        Panel_Degradado.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 50, 10));

        TXT_BOT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT.setText("CHAT BOT");
        TXT_BOT.setOpaque(true);
        Panel_Degradado.add(TXT_BOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 240, -1, -1));

        TXT_USER.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_USER.setForeground(new java.awt.Color(255, 255, 255));
        TXT_USER.setText("USUARIOS");
        TXT_USER.setOpaque(true);
        Panel_Degradado.add(TXT_USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 311, -1, -1));

        TXT_POSICION.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_POSICION.setForeground(new java.awt.Color(255, 255, 255));
        TXT_POSICION.setText("POSICIÓN");
        TXT_POSICION.setOpaque(true);
        Panel_Degradado.add(TXT_POSICION, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 380, -1, -1));

        TXT_GRAFICOS.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_GRAFICOS.setForeground(new java.awt.Color(255, 255, 255));
        TXT_GRAFICOS.setText("GRÁFICOS");
        TXT_GRAFICOS.setOpaque(true);
        Panel_Degradado.add(TXT_GRAFICOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 460, -1, -1));

        TXT_INFORMES.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_INFORMES.setForeground(new java.awt.Color(255, 255, 255));
        TXT_INFORMES.setText("INFORMES");
        TXT_INFORMES.setOpaque(true);
        Panel_Degradado.add(TXT_INFORMES, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 520, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(243, 244, 246));
        Panel_Degradado.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 550, 50, 10));

        jButton2.setBackground(new java.awt.Color(68, 73, 75));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_waypoint_map_30px.png"))); // NOI18N
        jButton2.setToolTipText("Oprime F1");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(true);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_waypoint_map_40px_1.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));
        jButton2.getAccessibleContext().setAccessibleDescription("");

        jButton3.setBackground(new java.awt.Color(68, 73, 75));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chat_Bot.png"))); // NOI18N
        jButton3.setToolTipText("Oprime F2");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setOpaque(true);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat_bot_38X49.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 40));

        jButton4.setBackground(new java.awt.Color(68, 73, 75));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar_Usuario.png"))); // NOI18N
        jButton4.setToolTipText("Oprime F3");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setOpaque(true);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_add_user_male_40px.png"))); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 40, 40));

        jButton5.setBackground(new java.awt.Color(68, 73, 75));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Posicion_.png"))); // NOI18N
        jButton5.setToolTipText("Oprime F4");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setOpaque(true);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_hunt_40px.png"))); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 40));

        jButton6.setBackground(new java.awt.Color(68, 73, 75));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estadisticos.png"))); // NOI18N
        jButton6.setToolTipText("Oprime F5");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(true);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_statistics_40px.png"))); // NOI18N
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, 40));

        jButton7.setBackground(new java.awt.Color(68, 73, 75));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resumen.png"))); // NOI18N
        jButton7.setToolTipText("Oprime F6");
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(true);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_document_40px.png"))); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 40, 40));

        jButton10.setBackground(new java.awt.Color(68, 73, 75));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_licence_40px.png"))); // NOI18N
        jButton10.setToolTipText("LICENCIA");
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setOpaque(true);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_licence_45px.png"))); // NOI18N
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Panel_Degradado.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 40, 50));

        TXT_LICENCIA.setForeground(new java.awt.Color(255, 255, 255));
        TXT_LICENCIA.setText("LICENCIA");
        TXT_LICENCIA.setOpaque(true);
        Panel_Degradado.add(TXT_LICENCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 630, -1, -1));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Degradado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Central_Cambiable, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu_Lateral_Derecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Lateral_Derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_Central_Cambiable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_Degradado, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1316, 754));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCenterMouseClicked


    }//GEN-LAST:event_pnlCenterMouseClicked

    private void MODO_NOCHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODO_NOCHEActionPerformed
       
    }//GEN-LAST:event_MODO_NOCHEActionPerformed

    private void ITEM_CICLOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_CICLOSActionPerformed
       
    }//GEN-LAST:event_ITEM_CICLOSActionPerformed

    private void ITEMA_CHAT_BOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMA_CHAT_BOTActionPerformed
      
    }//GEN-LAST:event_ITEMA_CHAT_BOTActionPerformed

    private void ITEM_USUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_USUARIOSActionPerformed
       
    }//GEN-LAST:event_ITEM_USUARIOSActionPerformed

    private void ITEM_POSICIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_POSICIONActionPerformed
       
    }//GEN-LAST:event_ITEM_POSICIONActionPerformed

    private void ITEM_ESTADISTICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_ESTADISTICOSActionPerformed
       
    }//GEN-LAST:event_ITEM_ESTADISTICOSActionPerformed

    private void ITEM_INFORMESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_INFORMESActionPerformed
      
    }//GEN-LAST:event_ITEM_INFORMESActionPerformed

    private void ITEM_MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEM_MENUActionPerformed
       
    }//GEN-LAST:event_ITEM_MENUActionPerformed

    private void MODO_DIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODO_DIAActionPerformed
       
    }//GEN-LAST:event_MODO_DIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem COPIAR;
    private javax.swing.JMenuItem ITEMA_CHAT_BOT;
    private javax.swing.JMenuItem ITEM_CICLOS;
    private javax.swing.JMenuItem ITEM_ESTADISTICOS;
    private javax.swing.JMenuItem ITEM_INFORMES;
    private javax.swing.JMenuItem ITEM_MENU;
    private javax.swing.JMenuItem ITEM_POSICION;
    private javax.swing.JMenuItem ITEM_USUARIOS;
    private javax.swing.JMenuItem MODO_DIA;
    private javax.swing.JMenuItem MODO_NOCHE;
    private javax.swing.JPanel Menu_Lateral_Derecho;
    private javax.swing.JMenuItem PEGAR;
    private javax.swing.JPanel Panel_Central_Cambiable;
    private org.netbeans.modules.form.InvalidComponent Panel_Degradado;
    private javax.swing.JLabel TXT_BOT;
    private javax.swing.JLabel TXT_CICLOS;
    private javax.swing.JLabel TXT_GRAFICOS;
    private javax.swing.JLabel TXT_INFORMES;
    private javax.swing.JLabel TXT_LICENCIA;
    private javax.swing.JLabel TXT_POSICION;
    private javax.swing.JLabel TXT_USER;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables

  
}
