/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

/**
 *
 * @author edwin
 */
public class Startt extends javax.swing.JPanel {

    /**
     * Creates new form Startt
     */
    public Startt() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Fondo = new javax.swing.JPanel();
        Menu_Lateral_Izquierdo_jPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        TXT_BOT = new javax.swing.JLabel();
        TXT_BOT1 = new javax.swing.JLabel();
        TXT_BOT2 = new javax.swing.JLabel();
        TXT_BOT3 = new javax.swing.JLabel();
        TXT_BOT4 = new javax.swing.JLabel();
        TXT_BOT5 = new javax.swing.JLabel();
        TXT_BOT6 = new javax.swing.JLabel();
        Panel_Central_Cambiable = new javax.swing.JPanel();
        Menu_Lateral_Derecho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        Panel_Fondo.setBackground(new java.awt.Color(204, 204, 204));

        Menu_Lateral_Izquierdo_jPanel.setBackground(new java.awt.Color(153, 153, 153));
        Menu_Lateral_Izquierdo_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 40, 50));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 40));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 40, 40));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 40));

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, 40));

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Izquierdo_jPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 40, 40));

        TXT_BOT.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT.setText("CICLOS");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, -1, -1));

        TXT_BOT1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT1.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT1.setText("LICENCIA");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 630, -1, -1));

        TXT_BOT2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT2.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT2.setText("CHAT BOT");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 240, -1, -1));

        TXT_BOT3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT3.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT3.setText("USUARIOS");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 311, -1, -1));

        TXT_BOT4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT4.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT4.setText("POSICIÓN");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 380, -1, -1));

        TXT_BOT5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT5.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT5.setText("GRÁFICOS");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 460, -1, -1));

        TXT_BOT6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TXT_BOT6.setForeground(new java.awt.Color(255, 255, 255));
        TXT_BOT6.setText("INFORMES");
        Menu_Lateral_Izquierdo_jPanel.add(TXT_BOT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 520, -1, -1));

        Panel_Central_Cambiable.setBackground(new java.awt.Color(244, 245, 247));
        Panel_Central_Cambiable.setLayout(new java.awt.CardLayout());

        Menu_Lateral_Derecho.setBackground(new java.awt.Color(51, 0, 51));
        Menu_Lateral_Derecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MENU");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu_Lateral_Derecho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, -1, -1));

        javax.swing.GroupLayout Panel_FondoLayout = new javax.swing.GroupLayout(Panel_Fondo);
        Panel_Fondo.setLayout(Panel_FondoLayout);
        Panel_FondoLayout.setHorizontalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_Lateral_Izquierdo_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Central_Cambiable, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu_Lateral_Derecho, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_FondoLayout.setVerticalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Central_Cambiable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Lateral_Derecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_FondoLayout.createSequentialGroup()
                        .addComponent(Menu_Lateral_Izquierdo_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu_Lateral_Derecho;
    private javax.swing.JPanel Menu_Lateral_Izquierdo_jPanel;
    private javax.swing.JPanel Panel_Central_Cambiable;
    private javax.swing.JPanel Panel_Fondo;
    private javax.swing.JLabel TXT_BOT;
    private javax.swing.JLabel TXT_BOT1;
    private javax.swing.JLabel TXT_BOT2;
    private javax.swing.JLabel TXT_BOT3;
    private javax.swing.JLabel TXT_BOT4;
    private javax.swing.JLabel TXT_BOT5;
    private javax.swing.JLabel TXT_BOT6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
